### ISSUE TITLE
We need a config file

### ISSUE THREAD

**Issue by ChristopherKossatz** [Maxklos/WeatherProjekt#5]
We need a config file.

as mentioned in the title, we need a config file for an easy setup process. There should be a config file for the Server and for the Client and should contain:
Client:     - Server ip + Port
Custom PiIp
Some information about the sensor or which Data should be send to the server 

Server: 
His own ip + port 
Database
Sensor and PiIp whitelist

Both should have an option to toggle the output completely

**Comment by Maxklos** [comment]
Great idea.  We could combine it with the setup script on the client. We should look how the guys at Pi-hole have done there setup. 

Edit :
Look at this 
https://github.com/pi-hole/pi-hole/blob/master/automated install/basic-install.sh

**Comment by Maxklos** [comment]
Projekt is Archived since 18.10.2023
